import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

		String gender = "";
		int index = 1;
		int num2Ch = 0;
		int num3Ch = 0;
		int num4Ch = 0;
		int sum = 0;
		int sum2;
		double average;
		
		for (int i = 0; i < T; i++){
			
			sum2 = 0;

				while(true) {			
			
					if (generator.nextDouble() < 0.5) {
			
						gender += "g ";

							} else {
			
								gender += "b ";
			
							}
			
					sum2++;
					sum++;
		
					if (index >= 3){

						if (gender.charAt(index - 1) != gender.charAt(index - 3)) {
				
							if (sum2 == 2) {

								num2Ch++;
								break;

								}  
					
							if (sum2 == 3) {

								num3Ch++;
								break;

								} 

							if (sum2 >= 4) {
						
								num4Ch++;
								break;
						
								}
						
					
							}
	
						}
			
					index += 2;

				}
		}	
	

		average = (double) sum/T;

		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + num2Ch);
		System.out.println("Number of families with 3 children: " + num3Ch);
		System.out.println("Number of families with 4 or more children: " + num4Ch);

		int mostCommon = Math.max(Math.max(num2Ch, num3Ch), num4Ch);
			
		if (num2Ch == mostCommon) {
			
			System.out.println("The most common number of children is 2.");

		}

		else if (num3Ch == mostCommon) {

			System.out.println("The most common number of children is 3.");
			
		}

		else if (num4Ch == mostCommon) {

			System.out.println("The most common number of children is 4 or more.");

		}
		    
	}
}
