import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {

		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);

        	Random generator = new Random(seed);  
		
		String gender = "";
		int num2Ch = 0;
		int num3Ch = 0;
		int num4Ch = 0;
		int sum = 0;
		int sum2;
		int index = 1;
		double average;
		
		for (int i = 0; i < T; i++){
			
			sum2 = 0;
			index = 1;
			gender = "";

			while(true) {			
				
				
				if (generator.nextDouble() < 0.5) {
			
					gender += "g ";

						} else {
			
							gender += "b ";
			
						}
			
				
				sum++;
				sum2++;
					
		
				if (index >= 3){

					if ((gender.charAt(index - 1) != gender.charAt(index - 3)) && (sum2 == 2)) {
							
							num2Ch++;
							break;
					}

					if ((gender.charAt(index - 1) != gender.charAt(index - 3)) && (sum2 == 3)) {
							
							num3Ch++;
							break;
					}

					if ((gender.charAt(index - 1) != gender.charAt(index - 3)) && (sum2 >= 4)) {
							
							num4Ch++;
							break;
					}


	
				}
			
				index += 2;

			}
		}	
	

		average = (double) sum/T;
		
		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + num2Ch);
		System.out.println("Number of families with 3 children: " + num3Ch);
		System.out.println("Number of families with 4 or more children: " + num4Ch);


		int mostCommon = Math.max(Math.max(num2Ch, num3Ch), num4Ch);
			
		if (num2Ch == mostCommon) {
			
			System.out.println("The most common number of children is 2.");

		}

		else if (num3Ch == mostCommon) {

			System.out.println("The most common number of children is 3.");
			
		}

		else if (num4Ch == mostCommon) {

			System.out.println("The most common number of children is 4 or more.");

		}
		    
	}
}
